In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\rithi\Downloads\tmdbdf.csv")

C:\Users\rithi\anaconda3\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [50]:
df=df.head(5000)

In [51]:
df

,Unnamed: 0,index,id,title,overview,keywords,genres,poster_path,tags
0,0,0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","rescue,mission,dream,airplane,paris,france,vir...","Action,ScienceFiction,Adventure",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,"cobb, a skilled thief who commits corporate es..."
1,1,1,157336,Interstellar,The adventures of a group of explorers who mak...,"rescue,future,spacecraft,raceagainsttime,artif...","Adventure,Drama,ScienceFiction",/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,the adventures of a group of explorers who mak...
2,2,2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"joker,sadism,chaos,secretidentity,crimefighter...","Drama,Action,Crime,Thriller",/qJ2tW6WMUDux911r6m7haRef0WH.jpg,batman raises the stakes in his war on crime. ...
3,3,3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","future,society,cultureclash,spacetravel,spacew...","Action,Adventure,Fantasy,ScienceFiction",/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,"in the 22nd century, a paraplegic marine is di..."
4,4,4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"newyorkcity,superhero,shield,basedoncomic,alie...","ScienceFiction,Action,Adventure",/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,when an unexpected enemy emerges and threatens...
...,...,...,...,...,...,...,...,...,...
4995,4995,4995,659959,Summer of 85,What do you dream of when you're 16-years-old ...,"basedonnovelorbook,sailing,normandy,france,mot...","Romance,Drama",/rkJKDC5gYrPXQx9IqNaUhSb3beC.jpg,what do you dream of when you're 16-years-old ...
4996,4996,4996,585378,After Yang,When his young daughter's beloved companion — ...,"future,basedonnovelorbook,lossoflovedone,adopt...","ScienceFiction,Drama",/qjEuDeKOhA7JqaaqhLSfoS9titb.jpg,when his young daughter's beloved companion — ...
4997,4997,4997,708577,Like a Cat on a Highway 2,Three years after her relationship with Giovan...,NaN,Comedy,/2dQ7CILvIXl1Yw0ZXtq5XYqjeqy.jpg,three years after her relationship with giovan...
4998,4998,4998,175574,Free Birds,Two turkeys from opposite sides of the tracks ...,"holiday,freedom,thanksgiving,duringcreditsstinger","Animation,Comedy,Family",/gnSU2wUBq2gTkBEkxY8C1d1fXAQ.jpg,two turkeys from opposite sides of the tracks ...
4999,4999,4999,4787,Cassandra's Dream,The tale of two brothers with serious financia...,"sailboat,siblingrelationship,lovetriangle,rest...","Crime,Drama,Thriller",/hydGWxW9VvRXMwpwFacl7XVtoeR.jpg,the tale of two brothers with serious financia...

In [52]:
df.isna().sum()

Unnamed: 0      0
index           0
id              0
title           0
overview        0
keywords       77
genres          0
poster_path     0
tags            0
dtype: int64

In [53]:
df.describe()

        Unnamed: 0        index            id
count  5000.000000  5000.000000  5.000000e+03
mean   2499.500000  2499.500000  1.656111e+05
std    1443.520003  1443.520003  2.294867e+05
min       0.000000     0.000000  5.000000e+00
25%    1249.750000  1249.750000  8.426250e+03
50%    2499.500000  2499.500000  2.433550e+04
75%    3749.250000  3749.250000  3.019452e+05
max    4999.000000  4999.000000  1.140066e+06

In [54]:
df.describe(include=object)

C:\Users\rithi\AppData\Local\Temp\ipykernel_48404\3998025828.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=object)

,title,overview,keywords,genres,poster_path,tags
count,5000,5000,4923,5000,5000,5000
unique,4888,5000,4900,1377,5000,5000
top,Pinocchio,"Cobb, a skilled thief who commits corporate es...",duringcreditsstinger,Comedy,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,"cobb, a skilled thief who commits corporate es..."
freq,4,1,5,246,1,1

In [55]:
df['tags'] = df['overview'].fillna(' ')+ df['keywords'].fillna(' ') + df['genres'].fillna(' ')
df['tags']

0       Cobb, a skilled thief who commits corporate es...
1       The adventures of a group of explorers who mak...
2       Batman raises the stakes in his war on crime. ...
3       In the 22nd century, a paraplegic Marine is di...
4       When an unexpected enemy emerges and threatens...
                              ...
4995    What do you dream of when you're 16-years-old ...
4996    When his young daughter's beloved companion — ...
4997    Three years after her relationship with Giovan...
4998    Two turkeys from opposite sides of the tracks ...
4999    The tale of two brothers with serious financia...
Name: tags, Length: 5000, dtype: str

In [56]:
df['tags'].isna().sum()

np.int64(0)

## Lower Case

In [57]:
df['tags']=df['tags'].apply(lambda x:x.lower())
df['tags']

0       cobb, a skilled thief who commits corporate es...
1       the adventures of a group of explorers who mak...
2       batman raises the stakes in his war on crime. ...
3       in the 22nd century, a paraplegic marine is di...
4       when an unexpected enemy emerges and threatens...
                              ...
4995    what do you dream of when you're 16-years-old ...
4996    when his young daughter's beloved companion — ...
4997    three years after her relationship with giovan...
4998    two turkeys from opposite sides of the tracks ...
4999    the tale of two brothers with serious financia...
Name: tags, Length: 5000, dtype: str

## Removing Tags and Puncuations

In [58]:
df['tags']=df['tags'].str.replace(r'[^\w\s]','',regex=True)

In [59]:
df['tags']

0       cobb a skilled thief who commits corporate esp...
1       the adventures of a group of explorers who mak...
2       batman raises the stakes in his war on crime w...
3       in the 22nd century a paraplegic marine is dis...
4       when an unexpected enemy emerges and threatens...
                              ...
4995    what do you dream of when youre 16yearsold and...
4996    when his young daughters beloved companion  an...
4997    three years after her relationship with giovan...
4998    two turkeys from opposite sides of the tracks ...
4999    the tale of two brothers with serious financia...
Name: tags, Length: 5000, dtype: str

## Stemming

In [60]:
from nltk.stem import PorterStemmer

In [61]:
ps=PorterStemmer()

In [62]:
ps.stem('running')

'run'

In [63]:
def stem(word):
    y=[]
    for i in word:
        y.append(ps.stem(i))
    return ' '.join(y)

In [64]:
df['tags']

0       cobb a skilled thief who commits corporate esp...
1       the adventures of a group of explorers who mak...
2       batman raises the stakes in his war on crime w...
3       in the 22nd century a paraplegic marine is dis...
4       when an unexpected enemy emerges and threatens...
                              ...
4995    what do you dream of when youre 16yearsold and...
4996    when his young daughters beloved companion  an...
4997    three years after her relationship with giovan...
4998    two turkeys from opposite sides of the tracks ...
4999    the tale of two brothers with serious financia...
Name: tags, Length: 5000, dtype: str

## Converting into vectors

In [65]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [66]:
tf = TfidfVectorizer(max_features=21000, stop_words = 'english')

In [67]:
vector = tf.fit_transform(df['tags'])

In [68]:
tf.get_feature_names_out().tolist()

['00',
 '006',
 '007',
 '10',
 '100',
 '1000',
 '10000',
 '100000',
 '1000foot',
 '100th',
 '101',
 '10191',
 '101yearold',
 '1021',
 '108yearold',
 '10b',
 '10round',
 '10yearold',
 '11',
 '117',
 '11th',
 '11year',
 '11yearold',
 '12',
 '120',
 '1200',
 '12hour',
 '12yearold',
 '13',
 '13yearold',
 '14',
 '1492',
 '14th',
 '14yearold',
 '15',
 '150',
 '15th',
 '15yearold',
 '16',
 '16th',
 '16year',
 '16yearold',
 '17',
 '17th',
 '17yearold',
 '18',
 '1800s',
 '1862',
 '1863',
 '1879',
 '1890s',
 '18th',
 '18yearold',
 '19',
 '1900',
 '1920s',
 '1925',
 '1927',
 '1930s',
 '1931',
 '1935',
 '1936',
 '1938',
 '1939',
 '1940',
 '1940s',
 '1941',
 '1942',
 '1944',
 '1945',
 '1947',
 '1949',
 '1950s',
 '1955',
 '1956',
 '1957',
 '1958',
 '1960',
 '1960s',
 '1962',
 '1963',
 '1964',
 '1965',
 '1967',
 '1968',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1977',
 '1978',
 '1979',
 '1980',
 '1980s',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1990',
 '1990s',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '19th',
 '19thcentury',
 '19yearold',
 '20',
 '200',
 '2000',
 '200000',
 '2002',
 '2003',
 '2004',
 '2008',
 '2009',
 '2010',
 '2013',
 '2015',
 '2016',
 '2019',
 '2028',
 '2029',
 '2035',
 '20th',
 '21st',
 '22',
 '22nd',
 '23',
 '23rd',
 '24',
 '24hour',
 '25',
 '25000',
 '26',
 '27',
 '28',
 '30',
 '300',
 '3000',
 '30s',
 '30th',
 '31',
 '35',
 '39',
 '40',
 '40s',
 '40yearold',
 '47',
 '50',
 '500',
 '50000',
 '50s',
 '51',
 '60',
 '600',
 '60s',
 '6yearold',
 '70',
 '70s',
 '72',
 '75',
 '80s',
 '8yearold',
 '90s',
 '911',
 '9yearold',
 'aaron',
 'aarons',
 'abandon',
 'abandoned',
 'abandons',
 'abbey',
 'abby',
 'abbys',
 'abduct',
 'abducted',
 'abductions',
 'abducts',
 'abe',
 'abigail',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abode',
 'abra',
 'abraham',
 'abrahams',
 'abroad',
 'abrupt',
 'absence',
 'absent',
 'absolutely',
 'absurd',
 'abuse',
 'abused',
 'abusive',
 'academic',
 'academies',
 'academy',
 'accept',
 'acceptance',
 'accepted',
 'accepting',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accidents',
 'acclaimed',
 'accompanied',
 'accompanies',
 'accompany',
 'accompanying',
 'accomplice',
 'accomplices',
 'accomplish',
 'accomplished',
 'according',
 'account',
 'accountant',
 'accounts',
 'accusations',
 'accused',
 'accuses',
 'ace',
 'achieve',
 'achieved',
 'achieves',
 'acme',
 'acquaintance',
 'acquaintances',
 'acquitted',
 'acre',
 'act',
 'action',
 'actionpacked',
 'actions',
 'actionthriller',
 'active',
 'activist',
 'activists',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'ad',
 'ada',
 'adaline',
 'adam',
 'adams',
 'adapt',
 'adaptation',
 'adapted',
 'adapting',
 'adaption',
 'adapts',
 'add',
 'addams',
 'addict',
 'addicted',
 'addiction',
 'adding',
 'addition',
 'additional',
 'address',
 'adds',
 'adelaide',
 'adele',
 'adjust',
 'adjustment',
 'adler',
 'administration',
 'admiral',
 'admired',
 'admiring',
 'admit',
 'admits',
 'admitted',
 'admonition',
 'adolescence',
 'adolescent',
 'adolf',
 'adonis',
 'adopt',
 'adopted',
 'adoption',
 'adoptive',
 'adopts',
 'adorable',
 'adoration',
 'adoring',
 'adrenaline',
 'adrenalinefueled',
 'adrian',
 'adrift',
 'adult',
 'adulthood',
 'adults',
 'advance',
 'advanced',
 'advances',
 'advancing',
 'advantage',
 'adventure',
 'adventurer',
 'adventures',
 'adventurous',
 'adversaries',
 'advertising',
 'advice',
 'advise',
 'adviser',
 'advisor',
 'advocate',
 'aerial',
 'affable',
 'affair',
 'affairs',
 'affected',
 'affection',
 'affections',
 'affects',
 'afflicted',
 'afford',
 'afghan',
 'afghanistan',
 'afoul',
 'afraid',
 'africa',
 'african',
 'africanamerican',
 'africas',
 'afterlife',
 'aftermath',
 'afternoon',
 'agamemnon',
 'agatha',
 'age',
 'aged',
 'ageing',
 'agency',
 'agencys',
 'agenda',
 'agent',
 'agents',
 'ages',
 'aggies',
 'aggression',
 'aggressive',
 'aggressively',
 'aging',
 'ago',
 'agree',
 'agreed',
 'agrees',
 'ahead',
 'ahsoka',
 'ai',
 'aiads',
 'aid',
 'aida',
 'aide',
 'aided',
 'aids',
 'ailing',
 'aim',
 'aimee',
 'aiming',
 'aimless',
 'aims',
 'air',
 'airborne',
 'aircraft',
 'airline',
 'airplane',
 'airport',
 'airports',
 'aj',
 'aka',
 'aki',
 'akira',
 'al',
 'alabama',
 'aladdin',
 'alan',
 'alarm',
 'alarming',
 'alaska',
 'alaskan',
 'albeit',
 'albert',
 'alberto',
 'album',
 'alcatraz',
 'alcohol',
 'alcoholic',
 'aldo',
 'aldous',
 'alec',
 'alejandro',
 'alert',
 'alex',
 'alexander',
 'alexandre',
 'alfie',
 'alfred',
 'algren',
 'ali',
 'alibi',
 'alice',
 'alices',
 'alicia',
 'alien',
 'alienated',
 'aliens',
 'alike',
 'alis',
 'alisdair',
 'alive',
 'allan',
 'allegations',
 'allegedly',
 'allegra',
 'allen',
 'allergic',
 'alley',
 'allfemale',
 'alliance',
 'alliances',
 'allied',
 'allies',
 'allnew',
 'allout',
 'allow',
 'allowed',
 'allowing',
 'allows',
 'allpowerful',
 'allstar',
 'allure',
 'ally',
 'alma',
 'almsy',
 'alongside',
 'aloof',
 'alpha',
 'alps',
 'als',
 'altar',
 'alter',
 'altered',
 'altering',
 'alternate',
 'alternative',
 'altruistic',
 'alvin',
 'alyssa',
 'alzheimers',
 'amanda',
 'amateur',
 'amazing',
 'amazon',
 'ambassador',
 'ambassadors',
 'amber',
 'ambition',
 'ambitions',
 'ambitious',
 'ambulance',
 'amelia',
 'amends',
 'america',
 'american',
 'americans',
 'americas',
 'amid',
 'amidst',
 'amish',
 'amity',
 'amnesia',
 'amok',
 'amsterdam',
 'amulet',
 'amusement',
 'amy',
 'ana',
 'anakin',
 'analyst',
 'anastasia',
 'ancestor',
 'anchor',
 'anchorman',
 'ancient',
 'anderson',
 'anderton',
 'andie',
 'andrew',
 'android',
 'andy',
 'andys',
 'angel',
 'angela',
 'angeles',
 'angelic',
 'angelov',
 'angels',
 'anger',
 'angers',
 'angry',
 'angst',
 'animal',
 'animals',
 'animated',
 'animation',
 'anime',
 'ann',
 'anna',
 'annabelle',
 'annas',
 'anne',
 'annie',
 'annies',
 'annihilation',
 'anniversary',
 'announcer',
 'announces',
 'annoy',
 'annoying',
 'annual',
 'anomaly',
 'anonymity',
 'anonymous',
 'anothers',
 'anselmi',
 'answer',
 'answered',
 'answers',
 'ant',
 'antarctica',
 'anthony',
 'anticipate',
 'anticommunist',
 'antics',
 'antidote',
 'antihero',
 'antique',
 'antiwar',
 'antoine',
 'anton',
 'antonio',
 'anxiety',
 'anxious',
 'anybody',
 'anymore',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apollo',
 'app',
 'appalachian',
 'apparent',
 'apparently',
 'apparitions',
 'appeals',
 'appear',
 'appearance',
 'appearing',
 'appears',
 'appetite',
 'apple',
 'applies',
 'apply',
 'appointed',
 'appoints',
 'appreciate',
 'appreciates',
 'apprehend',
 'apprehending',
 'apprentice',
 'approach',
 'approached',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'aquatic',
 'arab',
 'arabia',
 'aragorn',
 'aram',
 'aramis',
 'arcade',
 'archaeological',
 'archaeologist',
 'archenemy',
 'archer',
 'archibald',
 'architect',
 'architects',
 'archnemesis',
 'arctic',
 'arduous',
 'area',
 'areas',
 'arena',
 'arent',
 'argument',
 'ariel',
 'arise',
 'arises',
 'aristocrat',
 'aristocratic',
 'arizona',
 'ark',
 'arkansas',
 'arkin',
 'arm',
 'armada',
 'armand',
 'armed',
 'armies',
 'armor',
 'armored',
 'arms',
 'armstrong',
 'army',
 'armys',
 'arnie',
 'arnold',
 'arrange',
 'arranged',
 'arrangement',
 'arrangements',
 'arranges',
 'array',
 'arren',
 'arrest',
 'arrested',
 'arrests',
 'arrival',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'artemis',
 'arthur',
 'arthurs',
 'article',
 'artifact',
 'artifacts',
 'artificial',
 'artist',
 'artistic',
 'artists',
 'arts',
 'asami',
 'ascend',
 'ascension',
 'asgard',
 'asger',
 'ash',
 'ashitaka',
 'ashley',
 'ashore',
 'ashtray',
 'asia',
 'asian',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'asleep',
 'aspects',
 'aspen',
 'aspirations',
 'aspires',
 'aspiring',
 'assailant',
 'assassin',
 'assassinate',
 'assassinated',
 'assassinating',
 'assassination',
 'assassins',
 'assault',
 'assaulted',
 'assemble',
 'assembled',
 'assembles',
 'asset',
 'assets',
 'assign',
 'assigned',
 'assignment',
 'assignments',
 'assigns',
 'assist',
 'assistance',
 'assistant',
 'assistants',
 'assisted',
 'associate',
 'associates',
 'association',
 'assortment',
 'assume',
 'assumed',
 'assumes',
 'assuming',
 'asterix',
 'asteroid',
 'astonishing',
 'astounding',
 'astro',
 'astronaut',
 'astronauts',
 'astronomer',
 'asuka',
 'asylum',
 'athena',
 'athlete',
 'athletes',
 'athletic',
 'athos',
 'atlantic',
 'atlantis',
 'atmosphere',
 'atomic',
 'atone',
 'atreyu',
 'atrisk',
 'atrocious',
 'attached',
 'attachments',
 'attack',
 'attacked',
 'attacking',
 'attacks',
 'attempt',
 'attempted',
 'attempting',
 'attempts',
 'attend',
 'attendant',
 'attending',
 'attends',
 'attention',
 'attic',
 'attitude',
 'attorney',
 'attract',
 'attracted',
 'attracting',
 'attraction',
 'attractions',
 'attractive',
 'attracts',
 'aubrey',
 'audacious',
 'audacity',
 'audience',
 'audiences',
 'audition',
 'auditions',
 'audrey',
 'august',
 'augustus',
 'aunt',
 'aunts',
 'aurochs',
 'aurora',
 'auschwitz',
 'austin',
 'australia',
 'australian',
 'austrian',
 'author',
 'authorities',
 'authority',
 'autistic',
 'auto',
 'autobiographical',
 'autobots',
 'automaton',
 'automobile',
 'avail',
 'available',
 'avalanche',
 'avantgarde',
 'avatars',
 'avenge',
 'avenger',
 'avengers',
 'avenging',
 'avenue',
 'average',
 'avert',
 'avery',
 'aviation',
 'avoid',
 'avoided',
 'avoiding',
 'await',
 'awaited',
 'awaiting',
 'awaits',
 'awake',
 'awaken',
 'awakened',
 'awakening',
 'awakens',
 'awakes',
 'award',
 'aware',
 'away',
 'awesome',
 'awesomeness',
 'awkward',
 'awry',
 'axe',
 'axel',
 'babe',
 'babel',
 'babies',
 'baby',
 'babys',
 'babysitter',
 'bachelor',
 'bachelors',
 'backdrop',
 'backed',
 'background',
 'backgrounds',
 'backpackers',
 'backs',
 'backstage',
 'backwards',
 'backwoods',
 'backyard',
 'bad',
 'badge',
 'badly',
 'baffling',
 'bag',
 'baggage',
 'baggins',
 'bagheera',
 'bahamas',
 'bail',
 'bailey',
 'baker',
 'balance',
 'balboa',
 'baldwin',
 'ball',
 'ballerina',
 'ballet',
 'baloo',
 'balthazar',
 'baltimore',
 'bam',
 'bambino',
 'bamboo',
 'ban',
 'band',
 'bandit',
 'bandits',
 'bands',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'banking',
 'bankrupt',
 'bankruptcy',
 'banks',
 'banksy',
 'banned',
 'banner',
 'banning',
 'bar',
 'barbara',
 'barber',
 'barbie',
 'barcelona',
 'bare',
 'barely',
 'bargained',
 'barker',
 'barmaid',
 'barn',
 'barnes',
 'barney',
 'barnum',
 'baron',
 'barren',
 'barret',
 'barrier',
 'barrios',
 'barris',
 'barrow',
 'barry',
 'barrys',
 'bars',
 'barsoom',
 'bart',
 'bartender',
 'base',
 'baseball',
 'based',
 'basement',
 'basis',
 'basketball',
 'bass',
 'bassett',
 'basterds',
 'batch',
 'bates',
 'batman',
 'batmans',
 'batou',
 'battalion',
 'battle',
 'battled',
 'battlefield',
 'battlehardened',
 'battles',
 'battling',
 'bauby',
 'baxter',
 'bay',
 'baylor',
 'baz',
 'bc',
 'beach',
 'beaches',
 'beacon',
 'beam',
 'bean',
 'bear',
 'bearded',
 'bearer',
 'bearing',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beaten',
 'beating',
 'beatrice',
 'beats',
 'beau',
 'beaumont',
 'beauregard',
 'beautiful',
 'beauty',
 'bebop',
 'beca',
 'becca',
 'beck',
 'beckons',
 'bed',
 'bedroom',
 'bedtime',
 'bee',
 'beerus',
 'beethoven',
 'beezus',
 'befall',
 'befriend',
 'befriended',
 'befriending',
 'befriends',
 'began',
 'begbie',
 ...]

## Calculate The Similarity

In [69]:
from sklearn.metrics.pairwise import cosine_similarity

In [70]:
similarity = cosine_similarity(vector)

In [71]:
similaritydf = pd.DataFrame(similarity,index =df['title'],columns=df['title'])
similaritydf

title,Inception,Interstellar,The Dark Knight,Avatar,The Avengers,Deadpool,Avengers: Infinity War,Fight Club,Guardians of the Galaxy,Pulp Fiction,...,Undisputed II: Last Man Standing,The Fan,Demon Slayer: Kimetsu no Yaiba -To the Swordsmith Village-,Prey,Sunrise: A Song of Two Humans,Summer of 85,After Yang,Like a Cat on a Highway 2,Free Birds,Cassandra's Dream
title,,,,,,,,,,,,,,,,,,,,,
Inception,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.030408,0.000000,0.0,0.0,0.007137,0.008851,0.000000,0.000000,0.000000
Interstellar,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,0.028309,0.000000,0.000000,0.042613,...,0.000000,0.000000,0.019287,0.0,0.0,0.033402,0.000000,0.000000,0.044378,0.000000
The Dark Knight,0.000000,0.000000,1.000000,0.0,0.019004,0.000000,0.000000,0.000000,0.000000,0.019221,...,0.000000,0.007946,0.021296,0.0,0.0,0.000000,0.000000,0.018913,0.000000,0.028233
Avatar,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.016091,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
The Avengers,0.000000,0.000000,0.019004,0.0,1.000000,0.000000,0.008270,0.000000,0.015679,0.000000,...,0.000000,0.020978,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.021654,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Summer of 85,0.007137,0.033402,0.000000,0.0,0.000000,0.010271,0.000000,0.000000,0.000000,0.027742,...,0.013293,0.000000,0.000000,0.0,0.0,1.000000,0.007837,0.000000,0.000000,0.000000
After Yang,0.008851,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.015576,0.000000,0.000000,...,0.000000,0.000000,0.012781,0.0,0.0,0.007837,1.000000,0.000000,0.000000,0.000000
Like a Cat on a Highway 2,0.000000,0.000000,0.018913,0.0,0.000000,0.000000,0.000000,0.000000,0.057727,0.000000,...,0.000000,0.018113,0.000000,0.0,0.0,0.000000,0.000000,1.000000,0.000000,0.000000
Free Birds,0.000000,0.044378,0.000000,0.0,0.021654,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.015608,0.016155,0.000000,0.0,0.0,0.000000,0.000000,0.000000,1.000000,0.000000
Cassandra's Dream,0.000000,0.000000,0.028233,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.038349,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,1.000000

In [72]:
similaritydf['Inception'].sort_values(ascending=False)[1:6]

title
Abduction              0.125800
Charlie's Angels       0.110362
Elektra                0.108157
Possessor              0.103253
Law Abiding Citizen    0.099655
Name: Inception, dtype: float64

In [73]:
df[df['title'] == 'Avatar'].index[0]

3

In [74]:
import numpy as np
def recommend(movie):
    idx=df[df['title'] == movie].index[0]
    movie_list = np.argsort(similaritydf.iloc[idx])[::-1][1:6]
    return df.iloc[movie_list].title.tolist()

In [75]:
recommend('Avatar')

['The American',
 'The Matrix',
 'Apollo 18',
 'What Ever Happened to Baby Jane?',
 'Tears of the Sun']

In [76]:
df['poster_path']

0       /oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
1       /gEU2QniE6E77NI6lCU6MxlNBvIx.jpg
2       /qJ2tW6WMUDux911r6m7haRef0WH.jpg
3       /kyeqWdyUXW608qlYkRqosgbbJyK.jpg
4        /RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
                      ...
4995    /rkJKDC5gYrPXQx9IqNaUhSb3beC.jpg
4996    /qjEuDeKOhA7JqaaqhLSfoS9titb.jpg
4997    /2dQ7CILvIXl1Yw0ZXtq5XYqjeqy.jpg
4998    /gnSU2wUBq2gTkBEkxY8C1d1fXAQ.jpg
4999    /hydGWxW9VvRXMwpwFacl7XVtoeR.jpg
Name: poster_path, Length: 5000, dtype: str

In [77]:
baseurl = 'https://image.tmdb.org/t/p/w500/'
print(baseurl+'/8WqtunxSTVFiyBAUYSXbTSh0Vc5.jpg')

https://image.tmdb.org/t/p/w500//8WqtunxSTVFiyBAUYSXbTSh0Vc5.jpg

In [78]:
import pickle
with open(r"C:\Users\rithi\OneDrive\Documents\recommendation Unsupervised\project.pkl",'wb') as file:
    similarity = pickle.dump(similarity,file)